name: Get Subscription Weekly

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip3 install pyYAML requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Install tqdm
      run: |
        pip install tqdm

    - name: Collect Subscribe
      id: collect
      run: |
        cd aggregate
        python -u subscribe/collect.py -s
      
    - name: Create/Update Gist
      env:
        GH_TOKEN: ${{ secrets.PAT}}
      run: |
        cd aggregate/data
        gh gist edit ${{ secrets.GIST_ID }} --add "subscribes.txt"
        gh gist edit ${{ secrets.GIST_ID }} --add "domains.txt"
        gh gist edit ${{ secrets.GIST_ID }} --add "valid-domains.txt"

    - name: Read proxies.yaml
      id: read_proxies
      run: |
        content=$(cat proxies.yaml)
        echo "::set-output name=content::$content"

    - name: Gist Write Action
      uses: sergeysova/gist-write-action@v1.0.0
      with:
        gist_id: ${{ secrets.GIST_ID }} # 替换为你的Gist ID
        file_name: "proxies.yaml" # 替换为要写入的文件名
        content: ${{ steps.read_proxies.outputs.content }}
