name: Get Subscription Weekly

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip3 install pyYAML requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Install tqdm
      run: |
        pip install tqdm

    - name: Collect Subscribe
      id: collect
      run: |
        cd aggregate
        python -u subscribe/collect.py -s
      
    - name: Create/Update Gist
      env:
        GH_TOKEN: ${{ secrets.PAT}}
      run: |
        cd aggregate/data
        gh gist edit ${{ secrets.GIST_ID }} --add "subscribes.txt"
        gh gist edit ${{ secrets.GIST_ID }} --add "domains.txt"
        gh gist edit ${{ secrets.GIST_ID }} --add "valid-domains.txt"

    - name: Update Gist File
      env:
        GH_TOKEN: ${{ secrets.PAT }}
        GIST_ID: ${{ secrets.GIST_ID }}
      run: |
        cd aggregate/data
        # 使用 curl 命令清空 Gist 文件内容
        curl -X PATCH https://api.github.com/gists/$GIST_ID \
        -H "Authorization: token $GH_TOKEN" \
        -d '{"files": {"proxies.yaml": {"content": "" }}}'
        
        # 更新 Gist 文件
        # 假设 `proxies.yaml` 在当前目录下
        CONTENT=$(<proxies.yaml)
        JSON_CONTENT=$(jq -n --arg content "$CONTENT" '{"files": {"proxies.yaml": {"content": $content}}}')
        curl -X PATCH https://api.github.com/gists/$GIST_ID \
        -H "Authorization: token $GH_TOKEN" \
        -d "$JSON_CONTENT"
